import Head from "next/head";
import { api } from "~/utils/api";

export default function Offers() {
  const messages = api.listings.getMessage.useQuery();

  return (
    <>
      <Head>
        <title>Offers</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col gap-12 bg-gray-800">
        <h1 className="mt-12 pl-4 text-4xl">Your Offers</h1>
        <div className="container grid grid-cols-3 items-center justify-center gap-4">
          {messages?.data?.map((message) => (
            <div key={message.id}>{message.message}</div>
          ))}
        </div>
      </main>
    </>
  );
}
